[package]
name = "verilization-lang-scala"
version = "0.1.0"
authors = ["argon-dev <argon@argon.dev>"]
edition = "2018"

[dependencies]
verilization-compiler = { path = "../../compiler" }
nom = "6.1.2"
num-bigint = "0.4.0"
num-traits = "0.2.14"
pathdiff = "0.2.0"
lazy_static = "1.4.0"
